name: Build and Deploy to Azure

# Odpala się tylko przy pushu na main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   # Github starts the job on his ubuntu VM 

    steps:
      # Step 1 : Download the code from repo into the  VM runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run unit tests, if those fail , pipeline will fail 
      - name: Run unit tests
        run: |
          pip install -r requirements.txt --quiet
          pytest tests/ -v

      # Step 3: Login into docker hub , so that you can push the image there
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      # Step 4 : Build the image and push to docker hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: damgas712/gold-api:latest

      # Krok 5: zaloguj się do Azure używając service principal # Step 5 : Login into Azure using secrets
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 6 : Remove the old container and create a new one with new image
      - name: Redeploy ACI
        run: |
          az container delete \
            --resource-group gold-api-rg \
            --name gold-api \
            --yes

          az container create \
            --resource-group gold-api-rg \
            --name gold-api \
            --image damgas712/gold-api:latest \
            --registry-login-server index.docker.io \
            --registry-username ${{ secrets.DOCKERHUB_USERNAME }} \
            --registry-password ${{ secrets.DOCKERHUB_PAT }} \
            --ports 80 \
            --dns-name-label gold-api \
            --location westeurope \
            --os-type Linux \
            --cpu 1 \
            --memory 1.5 \
            --environment-variables \
                TWELVE_DATA_API_KEY=${{ secrets.TWELVE_DATA_API_KEY }} \
                FRED_API_KEY=${{ secrets.FRED_API_KEY }} \
                OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

      # Step 7 : Stop the container , to limit the costs (~$36/mies. 24/7) 
      # To start the ACI manually, run az container start --resource-group gold-api-rg --name gold-api-prediction-v2 
      - name: Stop ACI to save costs
        run: |
          az container stop \
            --resource-group gold-api-rg \
            --name gold-api
